CREATE TABLE IF NOT EXISTS orders (
    id VARCHAR(36) NOT NULL,
    shift_id VARCHAR(36) NOT NULL,
    cashier_id VARCHAR(36) NOT NULL,
    table_id VARCHAR(36) NULL,
    promo_id VARCHAR(36) NULL,
    status ENUM('draft','pending_payment','paid','cancelled') NOT NULL DEFAULT 'draft',
    subtotal BIGINT NOT NULL DEFAULT 0,
    discount_amount BIGINT NOT NULL DEFAULT 0,
    total BIGINT NOT NULL DEFAULT 0,
    notes TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_orders_shift_id (shift_id),
    KEY idx_orders_cashier_id (cashier_id),
    KEY idx_orders_status (status),
    KEY idx_orders_table_id (table_id),
    KEY idx_orders_promo_id (promo_id),
    CONSTRAINT fk_orders_shift_id FOREIGN KEY (shift_id) REFERENCES shifts (id),
    CONSTRAINT fk_orders_cashier_id FOREIGN KEY (cashier_id) REFERENCES users (id),
    CONSTRAINT fk_orders_table_id FOREIGN KEY (table_id) REFERENCES `tables` (id),
    CONSTRAINT fk_orders_promo_id FOREIGN KEY (promo_id) REFERENCES promos (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
